#!/bin/bash
#
# Regards, the Alveare Solutions society.
#
# QUICK INIT WRAPPER

PH_DIRECTORY="$(
    cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd
)"
${PH_DIRECTORY}/plaza-hotel 'client' $@
